(ns com.phronemophobic.membrandt.icon.twotone
  (:refer-clojure :only [defn defmacro let and])
  (:require [com.phronemophobic.membrandt.icon :as icon]
            [com.phronemophobic.membrandt.icon.impl.common :as common]
            [membrane.skia :as skia]
            [membrane.ui :as ui]
            [clojure.java.io :as io]))

(def icons
  #_(do
      (clojure.core/require '[com.phronemophobic.membrandt.icon.common :as common])
      (clojure.pprint/pprint
       (clojure.core/into #{}
                          (common/list-icons "twotone"))))
  #{"dashboard"
    "play-square"
    "file-pdf"
    "sound"
    "stop"
    "skin"
    "funnel-plot"
    "html5"
    "dislike"
    "message"
    "file-text"
    "info-circle"
    "minus-square"
    "contacts"
    "money-collect"
    "exclamation-circle"
    "left-square"
    "copyright-circle"
    "cloud"
    "printer"
    "save"
    "folder"
    "book"
    "file-unknown"
    "mail"
    "plus-circle"
    "calendar"
    "play-circle"
    "interaction"
    "star"
    "warning"
    "wallet"
    "security-scan"
    "file-image"
    "copy"
    "gold"
    "hourglass"
    "trademark-circle"
    "calculator"
    "shopping"
    "customer-service"
    "right-square"
    "delete"
    "ci"
    "euro"
    "alert"
    "unlock"
    "like"
    "gift"
    "project"
    "left-circle"
    "tags"
    "compass"
    "rocket"
    "sliders"
    "tablet"
    "profile"
    "smile"
    "crown"
    "camera"
    "right-circle"
    "diff"
    "box-plot"
    "dollar"
    "safety-certificate"
    "rest"
    "setting"
    "dollar-circle"
    "file-excel"
    "hdd"
    "euro-circle"
    "schedule"
    "fund"
    "tag"
    "appstore"
    "edit"
    "credit-card"
    "red-envelope"
    "down-circle"
    "eye"
    "build"
    "insurance"
    "database"
    "clock-circle"
    "up-square"
    "layout"
    "usb"
    "idcard"
    "close-square"
    "snippets"
    "bell"
    "filter"
    "control"
    "file-add"
    "file-zip"
    "pound-circle"
    "pushpin"
    "heart"
    "account-book"
    "experiment"
    "video-camera"
    "audio"
    "copyright"
    "home"
    "environment"
    "ci-circle"
    "phone"
    "shop"
    "api"
    "folder-add"
    "trophy"
    "picture"
    "car"
    "lock"
    "file-word"
    "carry-out"
    "up-circle"
    "tool"
    "file-markdown"
    "mobile"
    "file"
    "minus-circle"
    "meh"
    "question-circle"
    "highlight"
    "notification"
    "file-ppt"
    "switcher"
    "reconciliation"
    "pause-circle"
    "plus-square"
    "pie-chart"
    "property-safety"
    "down-square"
    "check-square"
    "bulb"
    "folder-open"
    "bug"
    "code"
    "bank"
    "flag"
    "check-circle"
    "frown"
    "container"
    "medicine-box"
    "fire"
    "file-exclamation"
    "close-circle"
    "eye-invisible"
    "thunderbolt"})

(common/deficons "twotone"
  {:primary-color "#1677ff"
   :secondary-color "#e6f4ff"})
